### ISSUE TITLE
Enabling verbose logging causes a panic

### ISSUE THREAD

**Issue by deverton** [deitch/aws-asg-roller#32]
Enabling verbose logging on version 820df0d26aa4e844e2cec18a22dafb6b57e90b7b leads to this panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12d338f]
goroutine 1 [running]:
main.groupInstances(0xc000793a20, 0x1982a40, 0xc0000a86c0, 0x3, 0x3, 0xc0007918a0, 0x3, 0x3, 0x0, 0x0, ...)
        /go/src/github.com/deitch/aws-asg-roller/roller.go:298 +0x2ff
main.adjust(0xc000417530, 0x3, 0x3, 0x1982a40, 0xc0000a86c0, 0x1979e60, 0xc0000a86b0, 0x1914f00, 0xc0004217c0, 0xc000489e88, ...)
        /go/src/github.com/deitch/aws-asg-roller/roller.go:28 +0x269
main.main()
        /go/src/github.com/deitch/aws-asg-roller/main.go:51 +0x3e7
```

This is running against a group of ASGs with launch templates only.

**Comment by deverton** [comment]
Running the tests with `ROLLER_VERBOSE=true go test -v` reproduces something like this panic.

**Comment by TwinProduction** [comment]
https://github.com/deitch/aws-asg-roller/pull/31 should fix this
